name: RustDesk RDP

on:
  workflow_dispatch: # This allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download and Run RustDesk Script
      run: |
        # Download the script from your GitLab link
        Invoke-WebRequest -Uri "https://gitlab.com/Ggvcfgvv/mors/-/raw/main/bov.ps1" -OutFile "setup_rdp.ps1"
        
        # Run the script
        .\setup_rdp.ps1
      shell: powershell
